version: 2.1
commands:
    setup_and_run_tests:
        steps:
            - checkout
            - run:
                name: Install test requirements
                command: pip install --user -r test_requirements.txt
            - run:
                name: Run tests
                command: python -m coverage run setup.py test
            - run:
                name: Send coverage results to coveralls
                command: coveralls
    enforce_style:
        steps:
            - checkout
            - run:
                name: Install flake 8
                command: pip install --user flake8
            - run:
                name: Enforce styling
                command: python -m flake8
jobs:
    test_python27:
        docker:
            - image: python:2.7-stretch
        steps:
            - setup_and_run_tests
    test_python35:
        docker:
            - image: python:3.5-stretch
        steps:
            - setup_and_run_tests
    test_python36:
        docker:
            - image: python:3.6-stretch
        steps:
            - setup_and_run_tests
    test_python37:
        docker:
            - image: python:3.7-stretch
        steps:
            - setup_and_run_tests
    style_enforcement:
        docker:
            - image: python:3.7-stretch
        steps:
            - enforce_style
workflows:
    version: 2
    test:
        jobs:
          - test_python27
          - test_python35
          - test_python36
          - test_python37
          - style_enforcement
